package com.backtester.infrastructure.persistence.mapper;

import com.backtester.domain.market.Bar;
import com.backtester.infrastructure.persistence.entity.BarEntity;
import org.springframework.stereotype.Component;

/**
 * Converts between {@link Bar} domain records and {@link BarEntity} JPA entities.
 * The entity's surrogate {@code id} is ignored during domain-to-entity conversion
 * (it is generated by the database on insert).
 */
@Component
public class BarEntityMapper {

    /**
     * Converts a domain {@link Bar} to a {@link BarEntity} ready for persistence.
     *
     * @param bar Domain record.
     * @return Corresponding JPA entity (no ID set; database assigns it on insert).
     */
    public BarEntity toEntity(Bar bar) {
        return new BarEntity(
                bar.ticker(),
                bar.date(),
                bar.open(),
                bar.high(),
                bar.low(),
                bar.close(),
                bar.volume()
        );
    }

    /**
     * Converts a persisted {@link BarEntity} to a domain {@link Bar}.
     *
     * @param entity JPA entity loaded from the database.
     * @return Immutable domain record.
     */
    public Bar toDomain(BarEntity entity) {
        return new Bar(
                entity.getTicker(),
                entity.getDate(),
                entity.getOpen(),
                entity.getHigh(),
                entity.getLow(),
                entity.getClose(),
                entity.getVolume()
        );
    }
}
